language: node_js

node_js:
  - 14

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres
  - psql -c "CREATE ROLE foo LOGIN SUPERUSER PASSWORD 'bar';" -U postgres

env:
  - DATABASE_URL=postgres://foo:bar@localhost:5432/travisdb SECRET=CyFjx6hEq34oycJanNdqsPzaGL7Y7K ADMIN_EMAIL=admin@suo.mi ADMIN_PASSWORD_HASH=$2b$10$oOet7XB1JmV7ocTTwYinV.s9Ql5s6tXRPwsYkZK39/PJGh6DT0tDC  # All used for testing only

