POST http://localhost:3001/api/customers
Content-Type: application/json

{
    "name": "Jack",
    "address": "Miami",
    "mobile": "045 1234567",
    "email": "jackkk@mi.ami",
    "password": "matinsalasana"
}