POST http://localhost:3001/api/orders
Content-Type: application/json

[
    {
        "product_id": 1,
        "priceAndSize": { "price": 140000, "size": "7 seater" },
        "quantity": 1
    },
    {
        "product_id": 2,
        "priceAndSize": { "price": 110000, "size": "5 seater" },
        "quantity": 2
    }
]